bind = Super Alt, Q, exec, dms ipc call powermenu toggle # Power Menu: Toggle
bind = Super, Comma, exec, dms ipc call settings toggle # Settings: Toggle
bind = Super, space, exec, dms ipc call spotlight toggle # App Launcher: Toggle
