# See https://wiki.hypr.land/Configuring/Monitors/
monitor = eDP-1, 2880x1800@120, 0x0, 1 # Monitor control for lid events

# Turn off screen when lid closes, turn on when it opens
bindl = , switch:on:Lid Switch, exec, hyprctl dispatch dpms off eDP-1
bindl = , switch:off:Lid Switch, exec, hyprctl dispatch dpms on eDP-1

