$background = 020305
$onBackground = e1e6ef
$surface = 020305
$surfaceDim = 020305
$surfaceBright = 0a0d11
$surfaceContainerLowest = 000000
$surfaceContainerLow = 030507
$surfaceContainer = 05070a
$surfaceContainerHigh = 06090c
$surfaceContainerHighest = 080b0f
$onSurface = e1e6ef
$surfaceVariant = 080b0f
$onSurfaceVariant = a6abb4
$outline = 70767e
$outlineVariant = 434850
$inverseSurface = f8f9fe
$inverseOnSurface = 535559
$shadow = 000000
$scrim = 000000
$surfaceTint = 1e2934
$primary = acc9ea
$primaryDim = 9ebcdc
$onPrimary = 25425d
$primaryContainer = 385571
$onPrimaryContainer = d0e5ff
$inversePrimary = 45617e
$primaryFixed = b7d5f6
$primaryFixedDim = a9c7e7
$onPrimaryFixed = 183651
$onPrimaryFixedVariant = 36536f
$secondary = b9c8da
$secondaryDim = acbacc
$onSecondary = 344150
$secondaryContainer = 2f3d4b
$onSecondaryContainer = b2c1d3
$secondaryFixed = d5e4f7
$secondaryFixedDim = c7d6e8
$onSecondaryFixed = 33414f
$onSecondaryFixedVariant = 4f5d6d
$tertiary = e0dcff
$tertiaryDim = d1ccfd
$onTertiary = 4f4b74
$tertiaryContainer = d1ccfd
$onTertiaryContainer = 46436b
$tertiaryFixed = d1ccfd
$tertiaryFixedDim = c3bfef
$onTertiaryFixed = 323057
$onTertiaryFixedVariant = 4f4c75
$error = fa746f
$errorDim = c54d4a
$onError = 490006
$errorContainer = 871f21
$onErrorContainer = ff9993
$primaryPaletteKeyColor = 5d7a97
$secondaryPaletteKeyColor = 6a7889
$tertiaryPaletteKeyColor = 76729e
$neutralPaletteKeyColor = 75777b
$neutralVariantPaletteKeyColor = 72777f
$errorPaletteKeyColor = c84f4c
$primary_paletteKeyColor = 5d7a97
$secondary_paletteKeyColor = 6a7889
$tertiary_paletteKeyColor = 76729e
$neutral_paletteKeyColor = 75777b
$neutral_variant_paletteKeyColor = 72777f
$term0 = 080808
$term1 = 8383ff
$term2 = 44def5
$term3 = 75fcdd
$term4 = 83b0cf
$term5 = 8fa9ee
$term6 = 8cd3f3
$term7 = ccdcd6
$term8 = 9aa59f
$term9 = a29eff
$term10 = 89ecff
$term11 = c9fff3
$term12 = a9c5d6
$term13 = abbdf8
$term14 = a8e4ff
$term15 = ffffff
$rosewater = f4f0fa
$flamingo = dfe0f5
$pink = d0ddff
$mauve = 9cc2ff
$red = 97b1ff
$maroon = aebdf1
$peach = e0c2f9
$yellow = d0f9f4
$green = b6e7ff
$teal = bee5ff
$sky = b9e0ff
$sapphire = 92cdff
$blue = 86c1ff
$lavender = abcfff
$klink = 428cc9
$klinkSelection = 428cc9
$kvisited = 4680db
$kvisitedSelection = 4580db
$knegative = 607eff
$knegativeSelection = 607eff
$kneutral = c794ff
$kneutralSelection = c794ff
$kpositive = 00b6ed
$kpositiveSelection = 00b6ec
$text = e1e6ef
$subtext1 = a6abb4
$subtext0 = 70767e
$overlay2 = 181919
$overlay1 = 151617
$overlay0 = 121315
$surface2 = 0e0f11
$surface1 = 090b0d
$surface0 = 030406
$base = 000001
$mantle = 000001
$crust = 000001
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
