preload = ~/Pictures/Wallpapers/macosgreyimage.jpg
wallpaper = eDP-1,~/Pictures/Wallpapers/macosgreyimage.jpg
splash = false
wallpaper {
  monitor = eDP-1
  path = ~/Pictures/Wallpapers/macosgreyimage.jpg
  fit_mode = cover
}

