# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:



exec-once = qs -c noctalia-shell
# exec-once = waybar &
# exec-once = swww-daemon
# exec-once = hypridle
#exec = hyprshade auto

# 1. Essential Environment Setup (All in one go)
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE
exec-once = sleep 1 && systemctl --user stop xdg-desktop-portal-hyprland xdg-desktop-portal && sleep 1 && systemctl --user start xdg-desktop-portal-hyprland

# 2. Start the Security Guard (Polkit)
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = sudo powertop --auto-tune

# exec-once = ~/.local/bin/nwg-dock.sh
# exec-once = xwaylandvideobridge &

#makes the computer not sound like its gonna fly away :)
exec-once = asusctl profile set quiet

exec-once = ~/.local/bin/zenbook_edge_handler.py

exec-once = flatpak run --command=valent ca.andyholmes.Valent --gapplication-service

# Workspace 1: Terminal
# exec-once = [workspace 1] foot

# Workspace 2: Zen Browser (Flatpak)
exec-once = [workspace 2 silent] ~/.local/bin/run_browser.sh

# Workspace 3: Google Meet
# exec-once = [workspace 3 silent] gnome-calendar

# Workspace 4: Gemini AI
# exec-once = [workspace 4 silent] ~/.local/bin/run_ai_assistant.sh

# Workspace 5: Spotify
exec-once = [workspace special:magic silent] spotify

# exec-once = gtk-launch com.rtosta.zapzap
# exec-once = gtk-launch com.rtosta.zapzap

exec-once = gnome-keyring-daemon --start --components=secrets,ssh,pkcs11

exec-once = /usr/lib/evolution-data-server/evolution-alarm-notify

exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
